# https://github.com/CircleCI-Public/circleci-demo-javascript-react-app
# https://circleci.com/docs/2.0/sample-config/
# https://circleci.com/docs/2.0/workflows/

# version 2.1 + orbs
# https://circleci.com/orbs/registry/orb/cypress-io/cypress
# https://circleci.com/orbs/registry/orb/thefrontside/react
# https://github.com/jeanbauer/cra-rtl-cypress-circleci

version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: cypress/base:10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  unit_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Unit tests
          command: npm run test

  e2e_tests:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Cypress e2e tests
          command: npm run cy:test

workflows:
  version: 2
  build_and_tests:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - e2e_tests:
          requires:
            - build
