# https://github.com/CircleCI-Public/circleci-demo-javascript-react-app
# https://circleci.com/docs/2.0/sample-config/
# https://circleci.com/docs/2.0/workflows/

version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  unit_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
        keys:
          - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Unit tests
          command: npm run test

  e2e_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
        keys:
          - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Cypress e2e tests
          command: npm run cy:run

workflows:
  version: 2
  build_and_tests:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - e2e_tests:
          requires:
            - build
